#!/bin/bash

if [[ `uname` == 'Darwin' ]]
then
    # NOTE The flag for dereferencing symlinks is
    # different on OS X (-h)

    ln -sfFh ~/.dotfiles/config ~/.config
    ln -sfFh ~/.dotfiles/emacs.d ~/.emacs.d
else
    ln -sfFn ~/.dotfiles/config ~/.config
    ln -sfFn ~/.dotfiles/emacs.d ~/.emacs.d
fi

ln -sf ~/.dotfiles/zsh/zshenv.sh ~/.zshenv
ln -sf ~/.dotfiles/zsh/zprofile.sh ~/.zprofile
ln -sf ~/.dotfiles/zsh/zshrc.sh ~/.zshrc

ln -sf ~/.dotfiles/gitconfig ~/.gitconfig

ln -sf ~/.dotfiles/xinitrc ~/.xinitrc
ln -sf ~/.dotfiles/Xresources ~/.Xresources
ln -sf ~/.dotfiles/Xmodmap ~/.Xmodmap
